const express = require('express')
const router = express.Router()
const UserDetail = require('../models/details')

//get Single User Data Using Autogenerated IDs
router.get('/getRecords/:userID', async (req, res) => {
    try{
   const SingleUser = await UserDetail.findById(req.params.userID)
   res.json({
       name: SingleUser.name,
       email: SingleUser.email
   })
    }catch(err){
        res.json({message: err})
    }
})

//Post a User Details
router.post('/setRecords', async (req, res) => {
    const post = new UserDetail({
        name: req.body.name,
        email: req.body.email
    })
    post.save()
    .then(data => {
        res.json(data)
    }).catch(err => {
        res.json({message: err})
    })
})

module.exports = router